"""Tests for the function of the create_dicomdir script."""

import os
from glob import glob

from pacsman.cli.create_dicomdir import (
    generate_new_folder_name,
    add_or_retrieve_name,
    move_and_rename_files,
    create_dicomdir,
)


def test_generate_new_folder_name():
    names = ["12345678", "abcdefgh"]
    name = generate_new_folder_name(names=names)
    assert name not in names
    assert len(name) <= 8
    assert len(name) >= 4
    assert name.isalnum()


def test_add_or_retrieve_name():
    old_2_new = {}
    names = []
    current_folder = "12345678"
    folder_name, old_2_new = add_or_retrieve_name(current_folder, old_2_new)
    assert folder_name not in names
    assert len(folder_name) <= 8
    assert len(folder_name) >= 4
    assert folder_name.isalnum()
    assert folder_name == old_2_new[current_folder]
    names.append(folder_name)

    current_folder = "abcdefgh"
    folder_name, old_2_new = add_or_retrieve_name(current_folder, old_2_new)
    assert folder_name not in names
    assert len(folder_name) <= 8
    assert len(folder_name) >= 4
    assert folder_name.isalnum()
    assert folder_name == old_2_new[current_folder]
    names.append(folder_name)


def test_move_and_rename_files(test_dir):
    dicom_path = os.path.join(test_dir, "tmp", "test_data", "dicomseries_structured")
    output_path = os.path.join(test_dir, "tmp", "test_data", "dicomseries_move_and_rename")
    if not os.path.exists(output_path):
        os.makedirs(output_path, exist_ok=True)
    move_and_rename_files(dicom_path, output_path)
    # Assess that the number of files in the output folder is the same
    # as in the input folder
    assert len(
        glob(os.path.join(output_path, "*", "*", "*", "*"))
    ) == len(
        glob(os.path.join(dicom_path, "*", "*", "*", "*"))
    )


def test_create_dicomdir(test_dir):
    # Employed the same output path generated by test_move_and_rename_files
    output_path = os.path.join(test_dir, "tmp", "test_data", "dicomseries_move_and_rename")
    create_dicomdir(output_path)
