name: pacsman_minimal
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip=19.2.3
  - Cerberus=1.3.2
  - hypothesis=6.0.2
  - nibabel=2.3.0
  - nipype
  - pandas=0.23.4
  - pydicom=1.4.1  # fixes package name
  - pytest=6.2.1
  - tqdm=4.43.0
