name: pacsman_min_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip=19.2.3
  - Cerberus=1.3.2 # 1.2
 # - chardet=3.0.4
  - hypothesis=6.0.2 # 3.71.3
  #- mock=2.0.0
  #- nose=1.3.7
  - nibabel=2.3.0
  - nipype
  #- numpy=1.15
  - pandas=0.23.4
  - pydicom=1.4.1  # fixes package name
  #- pyqt=4
  - pytest=6.2.1 # 3.7.4
  #- setuptools=40.2.0
  #- tinydb=3.11.0
  - tqdm=4.43.0
  #- typing=3.6.6 # built-in from python 3.5
  - pip:
    - datalad==0.10
    - inotify==0.2.10
    - ordereddict==1.1