name: pacsman_minimal
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=23.2.1
  # - Cerberus=1.3.2
  # - hypothesis=6.0.2
  # - nibabel=2.3.0
  # - nipype
  # - pandas=0.23.4
  # - pydicom=1.4.1  # fixes package name
  # - pytest=6.2.1
  # - tqdm=4.43.0
