name: dicom_minimal
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.5
  - Cerberus=1.2
  - chardet=3.0.4
  - datalad=0.10.2
  - hypothesis=3.71.3
  - mock=2.0.0
  - nose=1.3.7
  - nibabel=2.3.0
  - nipype
  - numpy=1.15
  - pandas=0.23.4
  - py=1.6.0
  - pydicom=0.9.9
  - pyqt=4
  - pytest=3.7.4
  - setuptools=40.2.0
  - six=1.11.0
  - tinydb=3.11.0
  - tqdm=4.25.0
  - typing=3.6.6
  - pip:
    - ordereddict==1.1
    - inotify==0.2.10
